version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: load-balancer
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./dockerconfig/nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  #MQTT
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - ./dockerconfig/mosquitto/config/:/mosquitto/config/
      - ./certbot/conf/:/mosquitto/certs/
    ports:
      - 1884:1883
      - 8883:8883
      - 9002:9001
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local