version: '3'

services:
  lb-server:
    image: nginx:latest
    container_name: lb-server
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: lb-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./certbot/conf/:/mosquitto/certs/
    ports:
      - 1884:1883
      - 8883:8883
      - 8083:8083
      - 9002:9001