version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./certbot/conf/:/mosquitto/certs/
    ports:
      - 1884:1883
      - 8883:8883
      - 8083:8083
      - 9002:9001
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge